# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Pricenometry
tagline:          'Follow. Analyze. Report.'
description:      'Track anything on the internet with a price tag. Easy to Use. Data updated daily. Free Trial Available. Follow us on Twitter <a href="https://twitter.com/pricenometry" target="_blank">@Pricenometry</a> or <a href="https://www.facebook.com/Pricenometry" target="_blank">Facebook</a>.'
url:              http://about.pricenometry.com
baseurl:          /

author:
  name:           'Michael Bastos'
  url:            https://twitter.com/bastosmichael

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/pricenometry
